ImageId: ami-1c323274
InstanceType: t2.medium
KeyPair: udnprod
ChefRole: fileservice
environment: production
InstanceName: fileservice
StackName: fileservice
cloudtype: aws
SecGroups:
    - fileserviceprod
AppServerAvailabilityZones:
    # us-east-1b and us-east-1c smell funny, skip those...
    - us-east-1a
    - us-east-1c
    - us-east-1d
LoadBalancer: true
AutoScalingGroupMaxSize: 1
AutoScalingGroupMinSize: 1
Tags:
 environment: production
