# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-03 16:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('filemaster', '0015_uuid_dehyphenate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required. 191 characters or fewer. Letters, numbers and @/./+/-/_/| characters', max_length=191, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-|]+$', 32), 'Enter a valid username.', 'invalid')], verbose_name='username'),
        ),
    ]
