# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemaster', '0016_auto_20190103_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivefile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
