# Generated by Django 2.2.15 on 2021-03-05 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemaster', '0020_remove_downloadlog_requesting_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filelocation',
            options={'ordering': ('-creationdate',), 'permissions': (('write_filelocation', 'Write filelocation'),)},
        ),
    ]
