# Generated by Django 2.2.15 on 2020-09-10 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filemaster', '0020_remove_downloadlog_requesting_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucket',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bucket',
            name='modifydate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
