# Generated by Django 2.2.15 on 2020-09-08 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filemaster.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filemaster', '0020_remove_downloadlog_requesting_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipartUpload',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('upload_id', models.TextField(editable=False)),
                ('size', models.IntegerField()),
                ('etag', models.TextField(blank=True, null=True)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(auto_now=True)),
                ('completeddate', models.DateTimeField(blank=True, null=True)),
                ('aborteddate', models.DateTimeField(blank=True, null=True)),
                ('expirationdate', models.DateTimeField(default=filemaster.models.week_from_now)),
                ('archivefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filemaster.ArchiveFile')),
                ('bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filemaster.Bucket')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filemaster.FileLocation')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=5242880)),
                ('index', models.IntegerField()),
                ('url', models.TextField()),
                ('etag', models.TextField(blank=True, null=True)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('modifydate', models.DateTimeField(auto_now=True)),
                ('completeddate', models.DateTimeField(blank=True, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='filemaster.MultipartUpload')),
            ],
        ),
    ]
