# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filemaster', '0021_archivefile_deletedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucket',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bucket',
            name='modifydate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
