# Generated by Django 2.2.19 on 2021-05-25 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemaster', '0021_auto_20210304_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='archivefile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filemaster.ArchiveFile'),
        ),
    ]
