# Generated by Django 2.2.15 on 2020-09-10 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemaster', '0021_auto_20200910_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivefile',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='bucket',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='filelocation',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='archivefile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filemaster.ArchiveFile'),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='requesting_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
